test: fix gcc 7.x compiler errors
GCC 7.x complains about the following in various locations
due to the way some of the GTEST macros are written:

	error: suggest explicit braces to avoid ambiguous
	'else' [-Werror=dangling-else]

Add explicit braces to our test code to fix this.

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>